sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MW1Wj5B6UaQuiwJIfManeNB5LPFHxv3HH29NnVxaoKi/HJgNasWrrQrPICOuJxDyirQlKo+24W/v5CJSKo5QZ+lLe5c59ewcdG1I8IQfYiJpdRPwLJHbSQtSbYN1xbfWMOvKfS2kanMA3PE5v7/VjAMERKToqmNDH7fpms/4ksgsBLU1tTSTWG7LAlS9z/80tb8KO30TBVjDlJQ436IGb6yoRp0qv5U0fxAkKd1YjbA8W49aSnWDIj4AqqSpvoeNqeeF/sgjrkYkqEliF7xqQKtjMV0aZONEocB+F/osBbaTUe+dGeW+5tkhjVOROW78BO6YkEK7h3mSmaeDU3E1W31px+fpnkxQ+EdDyj5s0mmJ/wNC/SB0AYo4nFfTXqpWaNV+beDkZ53p2Cd+S0YHSQfvWkING7rsq2/HpmiQSQ3y+EEKo7INlL4KlyFTfPlCBFLZPrR5A68qJH0jBDnr2Smo9S7VHsV1pxuFbMqHNy6wEvqyKwL4nMHqoVTu2An/Qyd0Qd856gIYcjdGlhl4pep58WpXhxSOG+jNEBU1XZCBKzWp3QW7xwB75cDwGxtvkx47o6tIBgPBJN9IF9UhKbgGSjffXOpwsJhJMLw6/LCMld3863XzS5cV8TsnGdLz+U8dY3YHRruBAuJ/w8+fy20Ftct8f2irbucw5Lhxypk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Bulfinch-s-Mythology--The-Age-of-Fable_3327
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy